# Site
repository: xuanhaihust/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dang Xuan Hai
title: AI Engineer / MLOps Engineer
email: haidx.hust@gmail.com
website: www.ecoai.pro

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: xuanhaihust
github_username:  xuanhaihust
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: xuanhaihust
# flickr_username: jekyll
instagram_username: xuanhaihust
linkedin_username: xuanhaihust
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: xuanhaihust
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: xuanhaihust.ecoai.pro
  icon: fas fa-globe
  url: http://xuanhai.ecoai.pro
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/ava.png
about_content: | # this will include new lines to allow paragraphs
  Hello, I'm Hai, an AI engineer, a quick learner and a self motivated person. My experiences lie on Computer Vision, Deep Learning, Data Analytics with 2 years working as an AI/ML engineer. My AI products have reached and enhanced the experience of millions of users.

  I am most skilled in: <mark>Computer Vision</mark> and <mark>Playing Board Game</mark>

  Here's my work [CV](https://drive.google.com/drive/folders/1AV3_2b4lTDeJLCgROyVMv0ObrHCeQR0u?usp=sharing){:target="_blank"}.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: OmegaOCR
        link: gitlab.com/pikachu-ai/omegaocr
        # link_text: Project Website
        additional_links:
          - title:  pikachu-ai/omegaocr
            icon: fab fa-gitlab
            url: gitlab.com/pikachu-ai/omegaocr
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          An end-to-end OCR application for document digitalization based on AI technology.  
        description: | # this will include new lines to allow paragraphs
          Many OCR apps/services today just return some raw texts of reading from input image. I've been searching for an app which can give me the document with exactly same format as the input image, what I really need, but I got no one good enough for Vietnamese document.
          As an engineer, I decided to make it myself.

          <mark>OmegaOCR</mark> utilizes the Deep Learning advantage to solve real life OCR problem, it contains a pipeline which receives images taken from any device such as smartphone camera (accept background), scanner... and reconstructs the digital document (.docx) with the same format as the input image, so that the document can be edited by end user..

          I have learned many skills through this and been I'm very proud of having this in my portfolio.

          For now, I'm trying to improve the OCR pipeline to archive higher performance, deploy the app as a cloud service and intergrate into mobile/web environment. The Demo Web interface can be found in project's repo.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Vingroup Bigdata Institute
        link: https://vinbigdata.org/en/
        # link_text: boringcompany.com
        sub_title: MLOps Engineer
        caption: October 2020 - Present
        quote: >
          Solving 21st century problems by taking advantage of AI and Big Data.
        description: | # this will include new lines to allow paragraphs
            - Research and develop ML model for [Thalassemia](https://www.cdc.gov/ncbddd/thalassemia/facts.html){:target="_blank"} detection problem.
            
            - Involve in AI project deployment process, perform DL model optimization. On production server, the optimized model is 3x faster and 4x lighter with just a little accuracy sacrifice.

      - layout: left
        title: Giao Hàng Tiết Kiệm., JSC
        link: https://giaohangtietkiem.vn/
        sub_title: AI Engineer
        caption: October 2019 - October 2020
        quote: >
          Change the Vietnam logistic and Ecommerce system, bring fast and cheap shipping service to everyone.
        description: | # this will include new lines to allow paragraphs
            - Our team aims to take advantage of AI technology to build smart features, provide best customer experience and high productivity.

            - As a key-person of the team, my responsibility was to collect, analyze, process the data and develop AI application to solve order routing, OCR, object detection problems. My AI products have reached and enhanced the experience of millions of users, supporting increase the productivity of company's logistic system.

            - Collaborate with Operations team for data, workflow understanding, feature requirements; DevOps team for deployment.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hanoi University of Science and Technology
        caption: 2019 - 2021
        sub_title: BSc Computer Science
        quote: >
          Established in 1958, HUST is the biggest and top science/engineering university in Vietnam.
        description: | # this will include new lines to allow paragraphs
          My 2nd degree at Hanoi University of Science and Technology (HUST). To learn IT, Programming fundamentals and Software Engineering.

      - layout: left
        title: Hanoi University of Science and Technology
        caption: 2013 - 2018
        sub_title: BSc Mechatronics Engineering
        description: |
          This is my first degree. It's a wonderful period of my life that I've been learned and explored a lot, experienced so many memorable things, and found out my passion in coding and Computer Vision - Image Processing.

          I spent most of my time learning major knowledges at school and research at Optical-Mechatronics Laboratory.
          In my free time, I tried to improve my soft skill such as English, presentation, teamwork... by taking a partime direct Sales position. I also participated in HUST Lean Six Sigma Club where I was the director of Communication Board.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in AI and Computer Vision, some of my other hobbies are:
      - Karate do, running
      - Board Game
      - Science Fiction Movies
      - [Writing](https://xuanhaihust.wordpress.com){:target="_blank"}
      - [Piano](https://www.youtube.com/watch?v=EgkZRYbpL_Y){:target="_blank"}


      Alright, so much information for today.  
      Look at this beautiful landscape, that's my hometown ^^  
      ![HaLongCity](/resume/images/hometown.jpg "Ha Long City"){: style="width:600px"}

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

markdown_extensions:
  - attr_list
